### ISSUE TITLE
Log in page: unhandled exception on attempt to log in with Google

### ISSUE THREAD

**Issue by agurtovoy** [uiowa-cs-5800-0001-fall-2018/blocklybot#12]
<img width="1414" alt="screen shot 2018-12-05 at 1 18 16 pm" src="https://user-images.githubusercontent.com/3394202/49538112-4fa51c80-f890-11e8-95f8-91053b26c125.png">

**Comment by hwaldstein** [comment]
This exception was due to old credentials still being cached. I have forced a refresh of the environment, which pulled the new credentials. Closing.
