### ISSUE TITLE
Home page: clicking on a "popular" project's View/Clone buttons has no effect

### ISSUE THREAD

**Issue by agurtovoy** [uiowa-cs-5800-0001-fall-2018/blocklybot#8]

**Comment by hwaldstein** [comment]
Professor, during the deploy to refresh tokens that I made yesterday, I believe I deployed an old version of the application. That's why the old version of the credentials was still there this morning. I don't believe this is accurate.

**Comment by agurtovoy** [comment]
Yep, this works now.
